# .github/workflows/cron.yml
name: Check and send to Vestaboard CRON Schedule

on:
  push:
    branches:
    - master
  schedule:
    # Runs "every 5 min from 6.00-22.00" (see https://crontab.guru)
    - cron: "*/5 4-19 * * *"
jobs:
  build:
    name: Check and send messages
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Next.js api
        run: |
          curl --request POST \
          --url 'https://vestaboard-beta.vercel.app/api/w3kvk3tzhrmf' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
